USER_CERT_FILE = '~/.centos.cert'
SERVER_CA_CERT_FILE = '~/.centos-server-ca.cert'
UPLOAD_CA_CERT_FILE = '~/.centos-upload-ca.cert'
FAS_TOPURL = 'https://accounts.centos.org'
FAS_CRL = 'https://accounts.centos.org/ca/crl.pem'
